apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-boilerplate-app
  labels:
    app: echo-boilerplate-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-boilerplate-app
  template:
    metadata:
      labels:
        app: echo-boilerplate-app
    spec:
      containers:
      - name: echo-boilerplate-app
        image: asia-southeast2-docker.pkg.dev/GOOGLE_PROJECT/go-image-repository/echo-boilerplate-app:latest
        ports:
        - containerPort: 1200
---