name: Build

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - id: Auth
        uses: google-github-actions/auth@v1
<<<<<<< HEAD
        with:
          credentials_json: '${{ secrets.JSON_KEY }}'

      - name: Set up Cloud CLI and install kubernetes plugin
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'gke-cloud-auth-plugin'
=======
        with:
          credentials_json: '${{ secrets.JSON_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
>>>>>>> c9fd134b1c65e6d330078b70478ac1104b202694
  
      - name: Build Docker Image
        run: docker build -t echo-boilerplate-app:latest .
      
      - name: Configure docker client of gcloud
<<<<<<< HEAD
        run: |-
=======
        run:  |-
>>>>>>> c9fd134b1c65e6d330078b70478ac1104b202694
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev 
          
      - name: Push Docker Image to Artifact Registry 
        env:
          PROJECT_ID: '${{ secrets.GOOGLE_PROJECT }}'
<<<<<<< HEAD
        run: |-
          docker tag echo-boilerplate-app:latest asia-southeast2-docker.pkg.dev/seeds-test-402504/go-image-repository/echo-boilerplate-app:latest
          docker push asia-southeast2-docker.pkg.dev/seeds-test-402504/go-image-repository/echo-boilerplate-app:latest

      - name: Deploy to Google Kubernetes Engine
        env:
          PROJECT_ID: '${{ secrets.GOOGLE_PROJECT }}'
        run: |-
          gcloud container clusters get-credentials golang-echo-cluster --region asia-southeast2
          sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" deployment.yaml
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml


=======
        run:  |-
          docker tag echo-boilerplate-app:latest asia-southeast2-docker.pkg.dev/seeds-test-402504/go-image-repository/echo-boilerplate-app:latest
          docker push asia-southeast2-docker.pkg.dev/seeds-test-402504/go-image-repository/echo-boilerplate-app:latest

        
>>>>>>> c9fd134b1c65e6d330078b70478ac1104b202694
    
