name: Build

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - id: Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.JSON_KEY }}'

      - name: Set up Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
  
      - name: Build Docker Image
        run: docker build -t echo-boilerplate-app:latest .
      
      - name: Configure docker client of gcloud
        run: |-
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev 
          
      - name: Push Docker Image to Artifact Registry 
        env:
          PROJECT_ID: '${{ secrets.GOOGLE_PROJECT }}'
        run: |-
          docker tag echo-boilerplate-app:latest asia-southeast2-docker.pkg.dev/seeds-test-402504/go-image-repository/echo-boilerplate-app:latest
          docker push asia-southeast2-docker.pkg.dev/seeds-test-402504/go-image-repository/echo-boilerplate-app:latest

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'golang-echo-cluster'
          location: 'asia-southeast2'

      - name: Deploy to Google Kubernetes Engine
        env:
          PROJECT_ID: '${{ secrets.GOOGLE_PROJECT }}'
        run: |-
          sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" deployment.yaml
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml


    
