name: Build

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - id: Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
  
      - name: Build Docker Image
        run: docker build -t echo-boilerplate-app:latest .
      
      - name: Configure docker client of gcloud
        run:  |-
          gcloud auth configure-docker 
          gcloud auth configure-docker asia-south2-docker.pkg.dev 
      
      - name: Push Docker Image to Artifact Registry 
        env:
          PROJECT_ID: '${{ secrets.GOOGLE_PROJECT }}'
        run:  |-
          docker tag echo-boilerplate-app:latest asia-southeast2-docker.pkg.dev/$PROJECT_ID/go-image-repository/echo-boilerplate-app:latest
          docker push asia-southeast2-docker.pkg.dev/$PROJECT_ID/go-image-repository/echo-boilerplate-app:latest

        
    
